name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry login
        run: |
          az acr login --name ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Check current directory
        run: |
          echo "Current directory: $(pwd)"
          ls -alh  # List files and directories to check if Dockerfile exists

      - name: Build Docker image
        run: |
          docker build -t simpleapptest.azurecr.io/simple-node-app:latest .

      - name: Push Docker image to ACR
        run: |
          docker push simpleapptest.azurecr.io/simple-node-app:latest
